- name: Main | Extracting Tutum UUID
  shell: cat /etc/tutum/agent/tutum-agent.conf | jq -r -c ".TutumUUID"
  register: extract_result
  until: extract_result.stdout != ""

- name: Main | Parsing Tutum UUID
  set_fact:
    tutum_agent_uuid: "{{ extract_result.stdout }}"

- name: Debug agent UUID
  debug: msg="Agent UUID - {{ tutum_agent_uuid }}"

- name: Main | Check node status
  shell: "curl -H \"Content-Type: application/json\" -H \"Authorization: {{ tutum_api_header }}\" {{ tutum_host ~ 'api/v1/node/' ~ tutum_agent_uuid ~ '/' }}"
  register: node_status
  until: node_status.stdout.find('\"Deployed\"') != -1
  retries: 10

- name: Main | Set node status
  set_fact:
    node_status: "{{ node_status.stdout.find('\"Deployed\"') }}"
