
- name: Debian OS installation | Adding repo
  template: src=debian/tutum.repo dest=/etc/apt/sources.list.d/tutum.list

- name: Debian OS installation | Installing dependencies #1
  apt: name=linux-image-extra-{{ ansible_kernel }} update_cache=yes state=present

- name: Debian OS installation | Installing dependencies #2
  apt: name=curl state=present

- name: Debian OS installation | Installing dependencies #3
  apt: name=jq state=present

- name: Debian OS installation | Importing GPG key
  shell: curl -Ls --retry 30 --retry-delay 10 {{ tutum_gpg_key }} | apt-key add -

# Request a token for the tutum agent
- include: request_token.yml

- name: Debian OS installation | Installing agent
  apt: name=tutum-agent update_cache=yes state=present