- name: Main  | Retrieving gpg key
  shell: curl -Ls --retry 30 --retry-delay 10 {{ tutum_gpg_key }} | gpg --import -

- name: Main | Tutum agent template
  template: src=tutum-agent.conf.j2 dest=/etc/tutum/agent/tutum-agent.conf
  notify:
    - Restart Tutum agent