---

- name: Main  | Retrieving gpg key
  shell: curl -Ls --retry 30 --retry-delay 10 {{ tutum_gpg_key }} | gpg --import -

- name: Main | Create Tutum config directory
  file: path=/etc/tutum/agent/ state=directory mode=0755

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Main | Restart tutum agent
  service:
     name: tutum-agent
     state: restarted

# set tags
- include: set_tags.yml
  when: tutum_tags is defined