---

- name: RedHat/CentOS installation  | Adding repo
  template: src=redhat/tutum.repo dest=/etc/yum.repos.d/tutum.repo

- name: RedHat/CentOS installation | Importing GPG key
  shell: rpm --import {{ tutum_gpg_key }}

- name: RedHat/CentOS installation | Installing dependencies
  yum: name=gpg,rpm,curl state=latest

- name: RedHat/CentOS installation | Installing agent
  yum: name=tutum-agent state=latest

- name: RedHat/CentOS - Install pip
  shell: "curl https://bootstrap.pypa.io/get-pip.py | python -"

- name: RedHat/CentOS installation | Installing httplib2
  pip: name=httplib2 state=latest
