---
- name: RedHat/CentOS installation | Importing GPG key
  shell: rpm --import {{ tutum_gpg_key }}

- name: RedHat/CentOS installation | Install EPEL
  yum: name=epel-release state=latest

- name: RedHat/CentOS installation | Installing dependencies
  yum: name=gpg,rpm,curl,python-pip,jq state=latest

- name: RedHat/CentOS installation | Installing httplib2
  pip: name=httplib2 state=latest
